console.log("Question.js is linked!");

var questions = [
    {
        question: "First things first. Choose a breakfast item: ",
        option1: "Broccoli & Cheese Quiche",
        option2: "Ham & Cheese Crossiants",
        option3: "Organic Chia Bars",
        option4: "Chocolate Babka",
        value1: 2.29,
        value2: 4.69,
        value3: 2.99,
        value4: 4.99,
        image1: "./images/quiche.jpg",
        image2: "./images/ham_cheese.jpg",
        image3: "./images/chia.jpg",
        image4: "./images/babka.jpeg"
    },
    {
        question: "One of your lunches gets to be a frozen meal! Choose one: ",
        option1: "Chicken Tikka Masala",
        option2: "Low Carb Mac n' Cheese",
        option3: "Chicken Burrito Bowl",
        option4: "Wild Salmon in Yogurt & Mint Sauce",
        value1: 2.99,
        value2: 1.99,
        value3: 3.49,
        value4: 4.49,
        image1: "./images/chicken_tikka.jpg",
        image2: "./images/mac_cheese.jpg",
        image3: "./images/burrito_bowl.jpg",
        image4: "./images/wild_salmon.jpg"
    },
    {
        question: "Choose a frozen source of protein:",
        option1: "Mandarin Orange Chicken",
        option2: "Organic Beef Sirloin Roast",
        option3: "Jumbo Sea Scallops",
        option4: "Quinoa Veggie Burgers",
        value1: 4.99,
        value2: 10.99,
        value3: 3.99,
        value4: 3.49,
        image1: "./images/mandarin_chicken.jpg",
        image2: "./images/beef_roast.jpg",
        image3: "./images/scallops.jpg",
        image4: "./images/veggie_burger.jpg"
    },
    {
        question: "Choose a side dish or a carb:",
        option1: "Riced Cauliflower",
        option2: "French Green Beans",
        option3: "Vegetable Fried Rice",
        option4: "Roasted Potatotes w/ Peppers & Onions",
        value1: 2.49,
        value2: 1.99,
        value3: 2.99,
        value4: 2.99,
        image1: "./images/cauliflower.png",
        image2: "./images/greenbeans.jpg",
        image3: "./images/friedrice.jpg",
        image4: "./images/roasted_pot.png"
    },
    {
        question: "Don't forget the best part. Choose a frozen appetizer:",
        option1: "Mini Chicken Cilantro Wontons",
        option2: "Chicken Satay Skewers",
        option3: "Mac & Cheese Bites",
        option4: "Puff Uncured Beef Dogs",
        value1: 2.99,
        value2: 4.49,
        value3: 3.49,
        value4: 6.49,
        image1: "./images/wontons.jpg",
        image2: "./images/satay.JPG",
        image3: "./images/cheese_bites.png",
        image4: "./images/puff_dogs.jpg"
    },
    {
        question: "Choose a frozen dessert:",
        option1: "Key Lime Pie Favorite",
        option2: "Salted Caramel Banana Pudding",
        option3: "Speculoos Cheesecake Bites",
        option4: "French Macarons",
        value1: 5.49,
        value2: 3.99,
        value3: 4.49,
        value4: 4.99,
        image1: "./images/keylime.jpeg",
        image2: "./images/salted_caramel.png",
        image3: "./images/speculoos.jpg",
        image4: "./images/macarons.jpg"
    },
    {
        question: "Choose a snack to munch on throughout the week: ",
        option1: "Cheese Snack Sticks",
        option2: "Cinnamon Apple Sticks",
        option3: "Sweetened Dry Orange Slices",
        option4: "Baked Green Pea Snack",
        value1: 2.99,
        value2: 2.49,
        value3: 3.49,
        value4: 1.99,
        image1: "./images/cheese_sticks.jpg",
        image2: "./images/apple_sticks.jpeg",
        image3: "./images/orange_slices.jpeg",
        image4: "./images/peas.jpg"
    },
    {
        question: "Choose something you don't need, but will get anyways:",
        option1: "Speculoos Cookie Butter",
        option2: "Ice Cream Sandwiches",
        option3: "Spinach & Artichoke Dip",
        option4: "Boddy Butter Trio",
        value1: 3.69,
        value2: 3.99,
        value3: 2.69,
        value4: 7.99,
        image1: "./images/speculoos_butter.jpg",
        image2: "./images/ice_cream.png",
        image3: "./images/artichoke_dip.jpg",
        image4: "./images/body_butter.jpg"
    },
    {
        question:
            "Wait, one more thing! Choose something last minute to add to cart:",
        option1: "Peanut Butter Cups",
        option2: "Green Tea Mints",
        option3: "One Greeting Card",
        option4: "Sipping Chocolate",
        value1: 0.99,
        value2: 1.99,
        value3: 0.99,
        value4: 3.99,
        image1: "./images/pbcups.jpg",
        image2: "./images/greentea.jpg",
        image3: "./images/card.jpg",
        image4: "./images/sipping.jpg"
    },
    {
        question:
            "Wait, one more thing! Choose something last minute to add to cart:",
        option1: "Peanut Butter Cups",
        option2: "Green Tea Mints",
        option3: "One Greeting Card",
        option4: "Sipping Chocolate",
        value1: 0.99,
        value2: 1.99,
        value3: 0.99,
        value4: 3.99,
        image1: "./images/pbcups.jpg",
        image2: "./images/greentea.jpg",
        image3: "./images/card.jpg",
        image4: "./images/sipping.jpg"
    }
];

//answer : 2
